MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  # WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  WEIGHT: /workspace/nd/pretrained_models/pytorch/resnet-50.pth 
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
DATASETS:
  # TRAIN: ("coco_2014_train", "coco_2014_valminusminival")
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (240000, 320000)
  MAX_ITER: 360000 
  IMS_PER_BATCH: 4  
  WARMUP_ITERS: 1000
  WARMUP_FACTOR: 0.166667 
