MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  # WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101"
  WEIGHT: /workspace/blued/model/pretrained_model_detectron/R-101.pkl 
  BACKBONE:
    CONV_BODY: "R-101-FPN"
    OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
INPUT:
  # MIN_SIZE_TRAIN: (600, 800, 1000, 1200)
  MIN_SIZE_TRAIN: 800 
  MAX_SIZE_TRAIN: 2000 
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1600
DATASETS:
  TRAIN: ("blued_0920_train", "qblued_20180803_train")
  TEST: ("blued_0920_test",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 8
SOLVER:
  BASE_LR: 0.03
  WEIGHT_DECAY: 0.0001
  # epoch_size=71383/16=4461.4
  STEPS: (105000, 145000)  # 24.36e, 32.46e 
  MAX_ITER: 163000  # 36.51e 
  IMS_PER_BATCH: 16 
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 5000   # 1e
TEST:
  TEST_WEIGHT: /workspace/blued/model/blued_v14.1_fR-101-FPN-2x-1209/model_final.pth 
